"""Type stub for the compiled Rust extension (``pycpfcnpj._speedups``).

The functions mirror the pure-Python core in ``pycpfcnpj._core``.
"""

def validate_cpf(cpf_number: str) -> bool: ...
def validate_cnpj(cnpj_number: str) -> bool: ...
def validate(number: str) -> bool: ...
